import "./lisp-tests.mjs";
import "./vm-test.mjs";
import "./eval-test.mjs";
import "./control-test.mjs";
import "./seq-test.mjs";
import "./stream-test.mjs";
import "./read-test.mjs";
import "./print-test.mjs";
import "./js-test.mjs";
