#!/usr/bin/env bash
set -Eeuo pipefail
cd $(realpath -Lm $(dirname ${BASH_SOURCE})/..)
# Run the main test suite in Node.
(set -x; ./node_modules/mocha/bin/mocha.js --slow 5000 --timeout 10000 dist/test/lispx-test-node.umd.js)
