#!/usr/bin/env bash
# I use this as a Git hook to always have up-to-date dist/ but it
# seems to be slightly broken (sometimes files in dist are missing
# from a commit...)
set -eux
yarn build
git add dist/
